import { useEffect, useMemo, useState } from 'react';
import { Navigate } from 'react-router-dom';
import { BarChart3, Package, Users, IndianRupee, RefreshCw, ShieldCheck, Truck, XCircle, Pencil, Trash2, Plus, Save, UserCheck, UserX } from 'lucide-react';
import { useAppDispatch, useAppSelector } from '@/redux/store';
import { updateOrderStatus, type Order } from '@/redux/slices/ordersSlice';
import { addToast } from '@/redux/slices/uiSlice';
import { Badge } from '@/components/ui/Badge';
import { Button } from '@/components/ui/Button';
import { fetchAdminOrders, fetchAdminProducts, fetchAdminUsers, isCurrentUserAdmin, updateAdminOrderStatus, upsertAdminProduct, deleteAdminProduct, signOutSupabase, type AdminUser } from '@/services/supabase';
import { supabase, supabaseEnabled } from '@/lib/supabase';
import { formatINR, formatDate } from '@/utils/format';
import { clearAdminSession } from '@/pages/AdminLogin';
import { products as seedProducts, replaceProducts } from '@/data/products';
import type { Product } from '@/types';

const statuses: Order['status'][] = ['Processing', 'Shipped', 'Out for Delivery', 'Delivered', 'Returned', 'Cancelled'];
type Tab = 'overview'|'orders'|'users'|'products';

export function AdminDashboard() {
  const dispatch = useAppDispatch(); const localOrders = useAppSelector((s) => s.orders);
  const [orders,setOrders]=useState<Order[]>(localOrders); const [users,setUsers]=useState<AdminUser[]>([]); const [products,setProducts]=useState<Product[]>([]);
  const [allowed,setAllowed]=useState(false); const [checking,setChecking]=useState(true); const [loading,setLoading]=useState(false); const [tab,setTab]=useState<Tab>('overview'); const [editing,setEditing]=useState<Product|null>(null);

  const load=async()=>{setLoading(true); const admin=supabaseEnabled ? await isCurrentUserAdmin() : false; setAllowed(admin); if(admin){
    if(supabaseEnabled){ const [o,u,p]=await Promise.all([fetchAdminOrders(),fetchAdminUsers(),fetchAdminProducts()]); if(!o.error&&o.data.length)setOrders(o.data.map(mapOrder)); if(!u.error)setUsers(u.data); if(!p.error)setProducts(p.data); }
    else setOrders(localOrders);
  } setChecking(false); setLoading(false);};
  useEffect(()=>{void load();},[]);

  const stats=useMemo(()=>({orders:orders.length,revenue:orders.reduce((s,o)=>s+o.total,0),pending:orders.filter(o=>['Processing','Shipped','Out for Delivery'].includes(o.status)).length,cancelled:orders.filter(o=>o.status==='Cancelled').length}),[orders]);
  const changeStatus=async(order:Order,status:Order['status'])=>{dispatch(updateOrderStatus({id:order.id,status}));setOrders(c=>c.map(o=>o.id===order.id?{...o,status}:o));if(supabaseEnabled){const r=await updateAdminOrderStatus(order.id,status);if(!r.ok)dispatch(addToast({message:'Unable to update order in Supabase.',type:'error'}));}};
  const seedCatalog=async()=>{if(!supabaseEnabled){dispatch(addToast({message:'Configure Supabase first.',type:'error'}));return;}setLoading(true);let count=0;for(const p of seedProducts){const r=await upsertAdminProduct(p);if(!r.error)count++;}setLoading(false);dispatch(addToast({message:`Published ${count} products to the admin catalog.`,type:'success'}));await load();};
  const saveProduct=async(p:Product)=>{const r=await upsertAdminProduct(p);if(r.error){dispatch(addToast({message:r.error.message,type:'error'}));return;}replaceProducts(products.some(x=>x.id===p.id)?products.map(x=>x.id===p.id?p:x):[p,...products]);setEditing(null);dispatch(addToast({message:'Product saved and published.',type:'success'}));await load();};
  const removeProduct=async(id:string)=>{if(!confirm('Delete this product from the catalog?'))return;const r=await deleteAdminProduct(id);if(r.error){dispatch(addToast({message:r.error.message,type:'error'}));return;}replaceProducts(products.filter(x=>x.id!==id));dispatch(addToast({message:'Product deleted.',type:'success'}));await load();};
  const changeRole=async(u:AdminUser)=>{if(!supabase)return;const next=u.role==='admin'?'customer':'admin';const r=await supabase.from('profiles').update({role:next}).eq('id',u.id);if(r.error){dispatch(addToast({message:r.error.message,type:'error'}));return;}await load();};

  if(checking)return <div className="mx-auto max-w-7xl px-4 py-20 text-center text-muted">Checking admin access…</div>; if(!allowed)return <Navigate to="/admin-login" replace/>;
  return <div className="mx-auto max-w-7xl px-4 py-6 lg:px-6">
    <div className="flex flex-wrap items-center justify-between gap-3"><div><p className="flex items-center gap-2 text-xs font-semibold uppercase tracking-widest text-stellar-500"><ShieldCheck className="h-4 w-4"/> Admin</p><h1 className="mt-1 text-2xl font-bold">Stellar Shop Control Center</h1><p className="mt-1 text-sm text-muted">Customers, orders and product catalog management.</p></div><div className="flex items-center gap-2"><Button variant="outline" onClick={()=>void load()} loading={loading}><RefreshCw className="h-4 w-4"/> Refresh</Button><Button variant="outline" onClick={()=>{clearAdminSession();void signOutSupabase();window.location.href='/admin-login';}}>Admin logout</Button></div></div>
    <div className="mt-6 flex gap-2 overflow-x-auto pb-1">{(['overview','orders','users','products'] as Tab[]).map(t=><button key={t} onClick={()=>setTab(t)} className={`rounded-full px-4 py-2 text-sm font-semibold capitalize ${tab===t?'gradient-stellar text-white':'border border-base hover:bg-soft'}`}>{t}</button>)}</div>
    {tab==='overview'&&<Overview stats={stats} users={users} products={products}/>} {tab==='orders'&&<OrdersTab orders={orders} changeStatus={changeStatus}/>} {tab==='users'&&<UsersTab users={users} changeRole={changeRole}/>} {tab==='products'&&<ProductsTab products={products} editing={editing} setEditing={setEditing} saveProduct={saveProduct} removeProduct={removeProduct} seedCatalog={seedCatalog} loading={loading}/>} 
  </div>;
}

function Overview({stats,users,products}:{stats:{orders:number;revenue:number;pending:number;cancelled:number};users:AdminUser[];products:Product[]}){return <><div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Stat icon={Package} label="Total orders" value={String(stats.orders)}/><Stat icon={IndianRupee} label="Order value" value={formatINR(stats.revenue)}/><Stat icon={Truck} label="Active orders" value={String(stats.pending)}/><Stat icon={XCircle} label="Cancelled" value={String(stats.cancelled)}/></div><div className="mt-6 grid gap-4 lg:grid-cols-2"><div className="rounded-card border border-base bg-elevated p-5"><h2 className="font-bold">Customer activity</h2><p className="mt-2 text-sm text-muted">{users.length} registered account(s). Recently active users are tracked by last login/last seen timestamps.</p><div className="mt-4 space-y-2">{users.slice(0,5).map(u=><div key={u.id} className="flex items-center justify-between rounded-lg bg-soft p-3"><span className="text-sm font-semibold">{u.name||'Unnamed'} · {u.email}</span><span className="text-xs text-muted">{u.last_login_at?formatDate(u.last_login_at):'No login recorded'}</span></div>)}</div></div><div className="rounded-card border border-base bg-elevated p-5"><h2 className="font-bold">Catalog</h2><p className="mt-2 text-sm text-muted">{products.length} product(s) are currently stored in the admin catalog.</p><p className="mt-4 text-xs text-muted">Use Products to change price, stock, images, description, tags or remove products.</p></div></div></>}

function OrdersTab({orders,changeStatus}:{orders:Order[];changeStatus:(o:Order,s:Order['status'])=>Promise<void>}){return <section className="mt-6 overflow-hidden rounded-card border border-base bg-elevated"><div className="border-b border-base p-4"><h2 className="flex items-center gap-2 font-bold"><BarChart3 className="h-5 w-5 text-stellar-500"/> Order management</h2></div><div className="divide-y divide-base">{orders.map(o=><div key={o.id} className="p-4"><div className="flex flex-wrap items-start gap-4"><div className="flex min-w-0 flex-1 gap-3"><img src={o.items[0]?.image||'/branding/product-placeholder.svg'} onError={fallbackImage} alt="" className="h-14 w-14 rounded-lg object-cover"/><div><div className="flex flex-wrap items-center gap-2"><p className="font-bold">{o.id}</p><Badge variant={o.status==='Delivered'?'success':['Cancelled','Returned'].includes(o.status)?'error':'stellar'}>{o.status}</Badge></div><p className="mt-1 text-sm text-muted">{o.items.length} item(s) · {formatINR(o.total)} · {formatDate(o.placedAt)}</p><p className="mt-1 text-xs text-muted">{o.address}</p></div></div><select value={o.status} onChange={e=>void changeStatus(o,e.target.value as Order['status'])} className="h-9 rounded-lg border border-base bg-base px-2 text-sm">{statuses.map(s=><option key={s}>{s}</option>)}</select></div></div>)}{orders.length===0&&<div className="p-10 text-center text-sm text-muted">No orders found.</div>}</div></section>}

function UsersTab({users,changeRole}:{users:AdminUser[];changeRole:(u:AdminUser)=>Promise<void>}){return <section className="mt-6 overflow-x-auto rounded-card border border-base bg-elevated"><table className="min-w-full text-sm"><thead className="border-b border-base bg-soft"><tr><th className="p-3 text-left">Name</th><th className="p-3 text-left">Email</th><th className="p-3 text-left">Mobile</th><th className="p-3 text-left">Address</th><th className="p-3 text-left">Role</th><th className="p-3 text-left">Last login</th><th className="p-3 text-left">Last seen</th><th className="p-3 text-left">Action</th></tr></thead><tbody className="divide-y divide-base">{users.map(u=><tr key={u.id}><td className="p-3 font-semibold">{u.name||'—'}</td><td className="p-3">{u.email}</td><td className="p-3">{u.mobile||'—'}</td><td className="max-w-xs p-3 text-xs text-muted">{u.address||'—'}</td><td className="p-3"><Badge variant={u.role==='admin'?'stellar':'default'}>{u.role}</Badge></td><td className="p-3 text-muted">{u.last_login_at?formatDate(u.last_login_at):'—'}</td><td className="p-3 text-muted">{u.last_seen_at?formatDate(u.last_seen_at):'—'}</td><td className="p-3">{u.role==='admin'?<Button size="sm" variant="outline" onClick={()=>void changeRole(u)}><UserX className="h-4 w-4"/> Make customer</Button>:<Button size="sm" variant="outline" onClick={()=>void changeRole(u)}><UserCheck className="h-4 w-4"/> Make admin</Button>}</td></tr>)}</tbody></table>{users.length===0&&<div className="p-10 text-center text-sm text-muted">No users found.</div>}</section>}

function ProductsTab({products,editing,setEditing,saveProduct,removeProduct,seedCatalog,loading}:{products:Product[];editing:Product|null;setEditing:(p:Product|null)=>void;saveProduct:(p:Product)=>Promise<void>;removeProduct:(id:string)=>Promise<void>;seedCatalog:()=>Promise<void>;loading:boolean}){return <section className="mt-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-lg font-bold">Product management</h2><p className="text-sm text-muted">Update price, stock, images and product content from the admin dashboard.</p></div><div className="flex gap-2"><Button variant="outline" onClick={()=>setEditing(newProduct())}><Plus className="h-4 w-4"/> Add product</Button>{products.length===0&&<Button onClick={()=>void seedCatalog()} loading={loading}>Publish starter catalog</Button>}</div></div>{editing&&<ProductEditor product={editing} onCancel={()=>setEditing(null)} onSave={saveProduct}/>}<div className="mt-5 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{products.map(p=><div key={p.id} className="rounded-card border border-base bg-elevated p-4"><div className="flex gap-3"><img src={p.images[0]||'/branding/product-placeholder.svg'} onError={fallbackImage} alt={p.name} className="h-20 w-20 rounded-xl object-cover"/><div className="min-w-0 flex-1"><p className="text-xs text-muted">{p.brand}</p><h3 className="font-bold">{p.name}</h3><p className="mt-1 text-sm">{formatINR(p.price)} · Stock {p.stock}</p><p className="mt-1 text-xs text-muted">{p.category}</p></div></div><div className="mt-3 flex gap-2"><Button size="sm" variant="outline" onClick={()=>setEditing(p)}><Pencil className="h-4 w-4"/> Edit</Button><Button size="sm" variant="outline" onClick={()=>void removeProduct(p.id)}><Trash2 className="h-4 w-4"/> Delete</Button></div></div>)}</div></section>}

function ProductEditor({product,onCancel,onSave}:{product:Product;onCancel:()=>void;onSave:(p:Product)=>Promise<void>}){const [p,setP]=useState(product);const set=(k:keyof Product,v:any)=>setP(x=>({...x,[k]:v}));return <div className="mt-5 rounded-card border border-stellar-300 bg-elevated p-5"><div className="flex items-center justify-between"><h3 className="font-bold">{product.id?'Edit product':'Add product'}</h3><Button size="sm" variant="outline" onClick={onCancel}>Cancel</Button></div><div className="mt-4 grid gap-3 md:grid-cols-2"><Input label="Name" value={p.name} onChange={v=>set('name',v)}/><Input label="Slug" value={p.slug} onChange={v=>set('slug',v)}/><Input label="Brand" value={p.brand} onChange={v=>set('brand',v)}/><Input label="Category" value={p.category} onChange={v=>set('category',v)}/><Input label="Price" value={String(p.price)} onChange={v=>set('price',Number(v)||0)} type="number"/><Input label="MRP" value={String(p.mrp)} onChange={v=>set('mrp',Number(v)||0)} type="number"/><Input label="Stock" value={String(p.stock)} onChange={v=>set('stock',Number(v)||0)} type="number"/><Input label="Image URLs (one per line)" value={p.images.join('\n')} onChange={v=>set('images',v.split('\n').map(x=>x.trim()).filter(Boolean))}/><div className="md:col-span-2"><label className="text-xs font-semibold text-muted">Description</label><textarea value={p.description} onChange={e=>set('description',e.target.value)} rows={4} className="mt-1.5 w-full rounded-xl border border-base bg-transparent p-3 text-sm outline-none"/></div></div><Button className="mt-4" onClick={()=>void onSave(p)}><Save className="h-4 w-4"/> Save & publish</Button></div>}
function Input({label,value,onChange,type='text'}:{label:string;value:string;onChange:(v:string)=>void;type?:string}){return <label><span className="text-xs font-semibold text-muted">{label}</span><input type={type} value={value} onChange={e=>onChange(e.target.value)} className="mt-1.5 h-10 w-full rounded-xl border border-base bg-transparent px-3 text-sm outline-none"/></label>}
function Stat({icon:Icon,label,value}:{icon:typeof Package;label:string;value:string}){return <div className="rounded-card border border-base bg-elevated p-4"><div className="flex items-center justify-between"><span className="text-sm text-muted">{label}</span><Icon className="h-5 w-5 text-stellar-500"/></div><p className="mt-2 text-2xl font-extrabold">{value}</p></div>}
function mapOrder(o:any):Order{return {id:o.id,items:o.items,total:Number(o.total),status:o.status,placedAt:o.placed_at,estimatedDelivery:o.estimated_delivery,address:o.address,paymentMethod:o.payment_method,cancellationReason:o.cancellation_reason||undefined,cancelledAt:o.cancelled_at||undefined};}
function newProduct():Product{return {id:`p-admin-${Date.now()}`,name:'New Product',slug:`new-product-${Date.now()}`,brand:'Brand',brandId:'b1',category:'Accessories',categoryId:'c17',price:0,mrp:0,rating:0,reviewCount:0,stock:0,images:['/branding/product-placeholder.svg'],colors:[],highlights:[],specs:[],description:'',warranty:'1 Year Manufacturer Warranty',returnPolicy:'10 days returnable',delivery:'Delivery by tomorrow',tags:[],createdAt:new Date().toISOString(),reviews:[]};}
function fallbackImage(e:React.SyntheticEvent<HTMLImageElement>){e.currentTarget.onerror=null;e.currentTarget.src='/branding/product-placeholder.svg';}
